#!/usr/bin/env ruby
# frozen_string_literal: true

require "w3c_validators"

def validator(file)
  extension = File.extname(file)
  if extension == ".html"
    W3CValidators::NuValidator.new
  elsif extension == ".css"
    W3CValidators::CSSValidator.new
  end
end

def validate(file)
  puts "Checking #{file}..."

  path = File.expand_path "../_site/#{file}", __dir__
  validator = validator(file)
  results = validator.validate_file(path)

  if results.errors.empty?
    puts "Valid!"
  else
    puts "Errors:"
    results.errors.each { |err| puts err }
    puts "Warnings:"
    results.warnings.each { |err| puts err }
    exit 1
  end
end


validate "index.html"
validate File.join "assets", "css", "style.css"
